### ISSUE TITLE
Is there a Java example app ?

### ISSUE THREAD

**Issue by suyashcjoshi** [dkurt/openvino_java#9]
Nice to the see the build artifacts but is there a working example of how to use Java APIs for Intel Open VINO? Also documentation such as Java Doc for the classes?

**Comment by dkurt** [comment]
Hi, @suyashjoshi! You may find it useful:
* [OpenVINO Java samples](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/java_api/samples)
* [OpenVINO Java tests](https://github.com/openvinotoolkit/openvino_contrib/tree/master/modules/java_api/tests)
* [OpenVINO in QuPath](https://github.com/dkurt/qupath-extension-openvino/blob/main/src/main/java/qupath/ext/openvino/OpenVINOBundle.java) - an extension for a digital pathology segmentation using OpenVINO
* [Android x86 demo](https://medium.com/@anna.likholat/sign-language-recognition-on-android-with-intel-openvino-1296d76bfa5e) - note that build instructions are outdated and old OpenVINO API is used

**Comment by suyashcjoshi** [comment]
This is excellent, thanks @dkurt !
